### ISSUE TITLE
Can't create a vm inside a zos-vm on the top of zos-host

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/0-initramfs#2]
## Scenario

1- Create a zos-vm on the top of a zos-host
2- Create a vm on the top of the zos-vm

Actual Result:
```
zeroos.core0.client.client.ResultError: "failed to create machine: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm ')"
```

Notes: 
Amzy was debugging in this, and here are some notes

1- Nested kvm is not activated on the zos-host
```
In [22]: cl.bash('cat /sys/module/kvm_intel/parameters/nested').get()
Out[22]: 
STATE: 0 SUCCESS
STDOUT:
N

STDERR:

DATA:
```

2- Also flag  ```-enable-kvm```  might need to be enabled

**Comment by delandtj** [comment]
Old cruft, closing to remove clutter from GH
