### ISSUE TITLE
iPXE IPv6 setting

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/0-initramfs#20]
for creating an iPXE bootloader for zOSv2, we'll need the iPXE lkrn with 

```
#define NET_PROTO_IPV4          /* IPv4 protocol */
#define NET_PROTO_IPV6          /* IPv6 protocol */
```
in `config/general.h`

so when a machine gets an IP addr via SLAAC and has a proper RouterAdvertisement Daemon (dnsmasq or radvd) on the SubnetZeroPrefix, we can boot a machine with IPv6.

then it can register itself.

I suspect we'll need to update [bootstrap.grid.tf](https://bootstrap.grid.tf) for that too

**Comment by maxux** [comment]
I'm reporting this to [0-bootstrap](https://github.com/threefoldtech/0-bootstrap), where the iPXE config is.

**Comment by maxux** [comment]
iPXE updated, bootstrap updated, please confirm it's all good for you and close this issue :)
