### ISSUE TITLE
Oops... no firmwares?

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/0-initramfs#29]
A lot of hardware drivers load firmware into cards prior to initializing them
Much needed would be FW for NICs and probably some for (i)scsi controllers.

`/lib/firmware` tends to be quite large from the onset, so we'll need to be selective

To wit :
`bnx* brcm* cxgb* myri* mellanox* netronome* qat* qed* ql2* qlogic* rt* RTL* ti*` (but without `rtlwifi`)

I suspect some FW for scsi controllers will still be missing, we'll see

**Comment by zaibon** [comment]
build with firmware as been tested and seems to work.
PR has been : https://github.com/threefoldtech/0-initramfs/pull/30
