### ISSUE TITLE
Can I please have bmon in the nodes ?

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/0-initramfs#34]
for a quick glance at network usage and pps, `bmon` would be a great tool... it's tiny but has immediate value  if things look fishy on the node's network

**Comment by delandtj** [comment]
https://github.com/tgraf/bmon

**Comment by delandtj** [comment]
debugfs would be cool too then :-)

**Comment by maxux** [comment]
Tool `bmon` added to default debugfs image.
