### ISSUE TITLE
ssh move default port to 34022

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/0-initramfs#38]
nodes with IPv6 will be accessible over ssh.
although it's all key besed, we should better move the port to something else than 22 to avoid being probed

**Comment by maxux** [comment]
SSH won't be included at all on the release images, so no need to fix AFAIK :)

**Comment by zaibon** [comment]
@maxux @delandtj 
The right way to propagate this on the node is to move the ssh server into the zos repo. and change the port there somehow.
During the next release the service will be added into the upgrade flist and apply during upgrade.

I'll move this issue to zos
