### ISSUE TITLE
Add smem to 0-OS

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/0-initramfs#8]
smem is a tool to properly see real memory usage per process, most importantly the relation between RSS PSS and USS

https://www.selenic.com/smem/

**Comment by maxux** [comment]
I don't think we need this on the initramfs. A privileged container to run this is enough, it's not really needed on the host;

**Comment by delandtj** [comment]
not sure... I'd like to add some primitives that call that thing from 0-OS, so we can at least call it from the client

**Comment by delandtj** [comment]
Closing this issue, won'fix (for now)
